[uwsgi]
chdir = /home/dmitry/autoparts_project
module = autoparts_shop.wsgi:application
home = /home/dmitry/autoparts_project/venv
master = true
processes = 4
socket = /home/dmitry/autoparts_project/autoparts.sock
chmod-socket = 666
vacuum = true
uid = dmitry
gid = dmitry
